export const SEARCH_CITY = "SEARCH_CITY";
export const GET_CITY_WEATHER = "GET_CITY_WEATHER";
export const INIT_DB = "INIT_DB";
export const UPDATE_CITY_WEATHER = "UPDATE_CITY_WEATHER";
export const UPDATE_DATABASE = "UPDATE_DATABASE";
export const SET_ACTIVE_CITY = "SET_ACTIVE_CITY";
export const REMOVE_CITY = "REMOVE_CITY";
